define config.default_music_volume = 1
define config.default_sfx_volume = 1

default evelynmove = False
default name = "Alex"
# default kcttut = True
default realmode = False
default tomhealth = 5
default showphone = False
default statspage = 1
default kctpage = 1
default itpage = 1
default fantasy = False
default stance = 0
default youdmg = 0
default youhealth = 5
default influencetut = False
# default ryrep4 = 0
# default ryrep5 = 0
# default larep8 = 0
# default larep9 = 0
default meetlauren = False
default laurenrs = False
# default jorep1 = 0
# default jorep4 = 0
# default jorep5 = 0
# default jorep7 = 0
# default jomsg = 0
# default joisreply = 0
# default joshnumber = False
# default larep4 = 0
# default larep5 = 0
default bro = 1
default boyfriend = 2
default troublemaker = 1
default loyal = bro * boyfriend / troublemaker
default popular = bro * troublemaker / boyfriend
default confident = boyfriend * troublemaker / bro
default phonetut = 1
# default emisreply = 0
# default auisreply = 0
# default emilymsg = 0
# default emrep1 = 0
# default aumsg = 0
# default aurep1 = 0
# default autumnmsgnot = 0
# default msgnot = 0
# default emilymsgnot = 0
default phonetutpage = 1
default realkcttut = 1
default statsnot = 0
default phoneexit = "phonea"
# default fantasiestut = 0
# default fantasiestutpage = 1
# default lauren_number = 0  - DELETE
# default laisreply = 0
# default larep1 = 0
# default larep2 = 0
# default larep3 = 0
# default lamsg = 0
# default lamsgnot = 0
default freeroamtut = 0
default freeroamtutpage = 1
default fr1riley = 0
default fr1elijah = 0
default fr1nora = 0
default fr1adam = 0
default funofelijah = 1
default chrisgone = 0
default endfrlabel = "efra"
default backfrlabel = "bfra"
default talktori = 0
default juliaismom = 0
# default juisreply = 0
# default jumsgnot = 0
# default jumsg = 0
# default jurep1 = 0
default laurenlike = 0
# default rymsg = 0
# default ryrep1 = 0
# default rymsgnot = 0
# default ryrep2 = 0
# default ryisreply = 0
# default ryfirst = 0
default fr2door = 0
default hitonnora = 0
default simtomfight = False
default simyou = 1
default simtom = 1
default tomdmg = 0
default tomattack = 1
default tomstance = 1
default reaction = 1.0
default reactiona = 1.0
default ischoice = False
default emilyandben = False
# default aubreynumber = False
# default aubmsgnot = 0
# default aubisreply = 0
# default aubmsg = 0
# default aubrep2 = 0
# default aubrep4 = 0
# default aubrep5 = 0
# default aubrep6 = 0
# default aubrep7 = 0
default forgiveemily = False
# default jomsgnot = 0
# default aubreyrep8 = 0
default costumeaubrey = True
default lakiss = 0
# default aubrep8 = 0
default caughtpeekingaubrey = False
default caughtpeekingpenelope = False
default try1done = False
default try2done = False
default try3done = False
default auboutfits = 0
default caughtpeekingaubreycounter = False
default try4done = False
default try5done = False
default try6done = False
default penoutfits = 0
default caughtpeekingpenelopecounter = False
default evelynnumber = False
# default evmsg = 0
# default evisreply = 0
# default evmsgnot = 0
default costume = 1
default w = "w"
default q = "q"
default e = "e"
default r = "r"
default qwer = True
default fighttom = False
default notcool = False
default difficulty = 1
default wton = False
default wt = 0
# default chloenumber = False
# default clmsg = 0
# default clisreply = 0
# default clmsgnot = 0
# default aubrep12 = 0
# default aubrep14 = 0
default laawk = True
default meetjulia = False
default openwound = False
default nohardfeelings = False
default keepitmoving = False
default romeo = False
default bigmouth = False
default mixedfeelings = False
default thenotorious = False
default anewbeginning = False
default overit = False
default rileykiss = False
default toldlauren = False
default laurenkissb = False
default laurentoofar = False
default dontanswerjulia = False
default notnowmom = False
default lipsdontlie = False
default truthhurts = False
default aubreysex = True
default revengeadam = False
default liejulia = False
default achievementsnot = 0 # Removed in next version
default girl = "Chloe"
default volleyball = False
# default clrep1 = 0
# default clrep3 = 0
default autumnmad = False
default muffin = False
default penelopekiss = False
default pornpen = 0
default bowling = False
# default jorep8 = 0
# default jorep12 = 0
# default jorep14 = 0
default shotamber = True
default kissamber = False
default kisskim = False
default tellnora = 0
# default ammsg = 0
# default ambernumber = False
# default amisreply = 0
# default amrep3 = 0
# default amrep4 = 0
# default amrep5 = 0
# default larep13 = 0
default laurenpublic = False
default la1 = True
default la2 = True
default la3 = True
default trolley = False
default trolleya = False
default trolleyb = False
default trolleyc = False
default laurenokay = True
default trolleyskip = 0
default relightthefire = False
default rematch = False
default keeneye = False
default chloemad = True
default apologize = False
default confrontadam = False
default fightadam = False
default tellschool = False
default adamtut = False
default adamfight = 5
default simadamfight = True
default adamdmg = 0
default adamstance = 1
default adamattack = 1
default adamhealth = 5
default simadam = 1
default winadam = False
default imremad = False
default firstfight = False
default hl = 0
# default amrep8 = 0
# default clrep5 = 0
default noexit = False
# default ammsgnot = 0
default onthelow = False
default petapublicenemy = False
default snitch = False
default chooseimre = True
default meetchloe = False
default imreforgives = False
# default clrep8 = 0
# default clrep6 = 0
# default amrep11 = 0
# default amrep12 = 0
# default amrep13 = 0
# default amrep16 = 0
default chloecaught = False
# default amrep17 = 0
# default amrep18 = 0
# default amrep21 = 0
# default clmsg4a = 0
# default ammsg17a = 0
# default ammsg21a = 0
# default clrep9 = 0
# default clmsg9a = 0
# default ammsg8a = 0
default kct = "popular"
default showkct = True
default v06 = True #kinda ;D
default temp_MessageNot = False
default firstkisslauren = False
#0.6
default laurenmad = False
default checkonrose = False
default evelyndate = False
default meetemily = False
default evelynrs = False
default kissevelyn = False
default meetaubrey = False
default aubrep16 = 0
default aubreysex2 = False
default aubreyrs = False
default aubmsg19a = 0
default aubrep19 = 0
default timed = False
default timerexit = "timera"
default moveuppercut = False
default joinapes = False
default pemsgnot = 0
default penelopenumber = False
default pemsg = 0
default peisreply = 0
default perep1 = 0
default perep3 = 0
default homeworkout = False
default amrep22 = 0
default amrep25 = 0
default msgaubrey19a = 0
default amrep24 = 0
default perform = 0
default kisspenelope = False
default takeshot = False
default meetgrayson = False
default kylie = True
default askfinn = False
default simp = False
default fr3josh = False
default fr3guy = False
default fr3aubrey = False
default fr3riley = False
default fr3chris = False
default fr3sebastian = False
default fr3amber = False
default fr3chloe = False
default fr3nora = False
default emilyrs = False
default noramad = False
default relics = 0
default fr3office = False
default askedkim = False
default askedaubrey = False
default askedemily = False
default askedriley = False
default askedamber = False
default upstairs = "nobody"
default kimpuke = False
default fr3matt = False
default save = 0
default brosbeforehoes = False
default credulous = False
default monkeybusiness = False
default notmybusiness = False
default reignition = False
default seemsfishy = False
default strike = False
#0.7
default follownora = False
default noraclose = True
default rileyrs = False
default kiwii = False
default penelopemad = False
default tellpenelope = False
default laurenemily = 0
default politics = False
default protest = False
default signs = False
default seenlauren = False
default laurenimre= False
default beachfirstkiss = False
default tasks = 0
default stoodUpToCam = False
default punchedCam = False
default cameronSisNumber = False # Cameron's little sister's number
default apesTask1 = False # Cameron telling MC to call Chloe
default wolvesTask1 = False
default wolvesTask2 = False
default wolvesTask3 = False
default wolvesTask4 = False
default madeFunOfLee = False
default apesTask2Try = False
default apesTask2Success = False
default joinwolves = True
default fr4chloe = False
default fr4ryan = False
default fr4aubrey = False
default fr4riley = False
default fr4aaron = False
default fr4cameron = False
default fr4mason = False
default fr4elijah = False
default fr4nora = False
default fr4nora2 = False
default fr4chris = False
default fr4lauren = False
default fr4msrose = False
default fr4penelope = False
default fr4imre = False
default fr4grayson = False
default fr4emily = False
default fr4samantha = False
default preventgrayson = False
default penelopesextoys = False
default penelopetruths = 0
default apesVids = 0
default cop = False
default bathroomblowjob = False
default ryandefendchloe = False
default focusonlauren = False
default chloesad = False
default lockerroomchloe = False
default fr4noriley = False
default fr4chloe2 = False
default rileysex = False
default ending = "riley"
default chloers = False
default amberrs = False
default penelopers = False
default walkedRileyHome = False
default amberEcstasyOffer = False # Whether Amber asked you to join her
default hcGirl = "na"
default hcAsked = [] # hcAsked.append("girl_name") to add
default consoledSam = False
default emilyText = False
default laurenpt = 0

default ecstatic = False
default homecomingqueen = False
default leeway = False
default playingwithfire = False
default silverback = False
default slowandsteady = False
default truetoself = False
default wolfpack = False

default nobeach = False




## Kiwii Vars
default kiwii_firstTime = True
