name: 🐛 Bug Report
description: File a bug report here
title: "ep4_s69b - Short description of the issue"
labels: ["type: bug", "priority: normal"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Don't forget to set the title by using the format:
        Episode & Scene Number followed by short description of the issue e.g. "ep2_s43a - Text typo"

  - type: checkboxes
    id: new-bug
    attributes:
      label: Is there an existing issue for this?
      description: Please search under [Issues](https://github.com/College-Kings/College-Kings-2/issues) to see if an issue already exists for the bug you are about to report.
      options:
        - label: I have searched the existing issues
          required: true

  - type: input
    id: scene-id
    attributes:
      label: Scene number
      description: We need episode version & scene number (e.g. ep2_s41b)
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: |
        What priority would you consider this issue to be?
        ℹ️ **URGENT** - The issue is causing the game to crash and the player cannot progress through the story. The game is considered unplayable.
         ❗ URGENT should ONLY be applicable if the game is launched to the general public. This should NOT be used when testing the game. ❗
        ℹ️ **High** - Any issue causing the game to crash or the story to break.
        ℹ️ **Normal** - For issues that are currently not affecting any crucial part(s) of the game
        ℹ️ **Low** - Issue that we should keep in mind and address at some point. Not affecting anything in particular, minor bug.
      multiple: false
      options:
        - Low
        - Normal
        - High
        - Urgent
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      # placeholder: 
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      # placeholder: 
    validations:
      required: false

  - type: textarea
    id: additional-info
    attributes:
      label: Additional context
      description: |
        Videos? Screenshots? Anything that will give us more context about the issue you are encountering!
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      # placeholder: 
    validations:
      required: false

  - type: dropdown
    id: environment
    attributes:
      label: What is the OS version you are playing on?
      description: If you select "Other", please provide the OS name and version in the box above.
      multiple: false
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true
