default msgApp = Application("Messages", "images/messagesicon.webp", "contactsscreen")
default statsApp = Application("Stats", "images/statsicon.webp", "stats", locked=True)
default achApp = Application("Achievements", "images/achicon.webp", "achievements")
default kiwiiApp = Application("Kiwii", "images/Phone/Kiwii/AppAssets/kiwii.webp", "kiwiiApp", locked=True)
default fightApp = Application("Fight App", "images/statsicon.webp", "fightApp")
default simplrApp = Application("Simplr", "images/statsicon.webp", "simplrApp")

default contact_Emily = Contact("Emily", "emilyprofilepic", locked=False)
default contact_Lauren = Contact("Lauren", "laurenprofilepic")
default contact_Julia = Contact("Julia", "juliaprofilepic")
default contact_Ryan = Contact("Ryan", "ryanprofilepic")
default contact_Josh = Contact("Josh", "joshprofilepic")
default contact_Aubrey = Contact("Aubrey", "aubreyprofilepic")
default contact_Chloe = Contact("Chloe", "chloeprofilepic")
default contact_Evelyn = Contact("Evelyn", "evelynprofilepic")
default contact_Amber = Contact("Amber", "amberprofilepic")
default contact_Penelope = Contact("Penelope", "penelopeprofilepic")
default contact_Riley = Contact("Riley", "rileyprofilepic")
default contact_Autumn = Contact("Autumn", "autumnprofilepic")
default contact_Imre = Contact("Imre", "imreprofilepic")
default contact_Sebastian = Contact("Sebastian", "sebastianprofilepicture")
default contact_Grayson = Contact("Grayson", "graysonprofilepicture")
default contact_Lindsey = Contact("Lindsey", "lindseyprofilepic")