default msgApp = Application("Messages", "messages/appAssets/messagesIcon.webp", "contactsscreen")
default statsApp = Application("Stats", "stats/appAssets/statsIcon.webp", "stats", locked=True)
default achApp = Application("Achievements", "achievements/appAssets/achievementsIcon.webp", "achievements")
default kiwiiApp = Application("Kiwii", "kiwii/appAssets/kiwiiIcon.webp", "kiwiiApp", locked=True)
default fightApp = Application("Fights", "fights/appAssets/messagesIcon.webp", "fightApp", locked=True)
default simplrApp = Application("Simplr", "simplr/appAssets/simplrIcon.webp", "simplr_app", locked=True)

default contact_Emily = Contact("Emily", "emilyprofilepic.webp")
default contact_Lauren = Contact("Lauren", "laurenprofilepic.webp")
default contact_Julia = Contact("Julia", "juliaprofilepic.webp")
default contact_Ryan = Contact("Ryan", "ryanprofilepic.webp")
default contact_Josh = Contact("Josh", "joshprofilepic.webp")
default contact_Aubrey = Contact("Aubrey", "aubreyprofilepic.webp")
default contact_Chloe = Contact("Chloe", "chloeprofilepic.webp")
default contact_Evelyn = Contact("Evelyn", "evelynprofilepic.webp")
default contact_Amber = Contact("Amber", "amberprofilepic.webp")
default contact_Penelope = Contact("Penelope", "penelopeprofilepic.webp")
default contact_Riley = Contact("Riley", "rileyprofilepic.webp")
default contact_Autumn = Contact("Autumn", "autumnprofilepic.webp")
default contact_Imre = Contact("Imre", "imreprofilepic.webp")
default contact_Sebastian = Contact("Sebastian", "sebastianprofilepicture.webp")
default contact_Grayson = Contact("Grayson", "graysonprofilepicture.webp")
default contact_Lindsey = Contact("Lindsey", "lindseyprofilepic.webp")
default contact_Jenny = Contact("Jenny", "jennyprofilepicture.webp")