#region v1.0
image no_hard_feelings = "achievements/images/v1/nohardfeelings.webp"
image open_wound = "achievements/images/v1/openwound.webp"
image keep_it_moving = "achievements/images/v1/keepitmoving.webp"
image romeo = "achievements/images/v1/romeo.webp"
image big_mouth = "achievements/images/v1/bigmouth.webp"
#endregion v1.0

image mixed_feelings = "achievements/images/v2/mixedfeelings.webp"
image the_notorious = "achievements/images/v2/thenotorious.webp"
image a_new_beginning = "achievements/images/v2/anewbeginning.webp"
image over_it = "achievements/images/v2/overit.webp"

image not_now_mom = "achievements/images/v3/notnowmom.webp"
image lips_dont_lie = "achievements/images/v3/lipsdontlie.webp"
image truth_hurts = "achievements/images/v3/truthhurts.webp"

image relight_the_fire = "achievements/images/v4/relightthefire.webp"
image rematch = "achievements/images/v4/rematch.webp"
image keen_eye = "achievements/images/v4/keeneye.webp"

image on_the_low = "achievements/images/v5/onthelow.webp"
image peta_public_enemy = "achievements/images/v5/petapublicenemy.webp"
image snitch = "achievements/images/v5/snitch.webp"

image bros_before_hoes = "achievements/images/v6/brosbeforehoes.webp"
image credulous = "achievements/images/v6/credulous.webp"
image not_my_business = "achievements/images/v6/notmybusiness.webp"
image reignition = "achievements/images/v6/reignition.webp"
image monkey_business = "achievements/images/v6/monkeybusiness.webp"
image seems_fishy = "achievements/images/v6/seemsfishy.webp"
image strike = "achievements/images/v6/strike.webp"

image true_to_self = "achievements/images/v7/truetoself.webp"
image silverback = "achievements/images/v7/silverback.webp"
image wolfpack = "achievements/images/v7/wolfpack.webp"
image lee_way = "achievements/images/v7/lee-way.webp"
image ecstatic = "achievements/images/v7/ecstatic.webp"
image slow_and_steady = "achievements/images/v7/slowandsteady.webp"
image playing_with_fire = "achievements/images/v7/playingwithfire.webp"
image homecoming_queen = "achievements/images/v7/homecomingqueen.webp"

image get_a_room = "achievements/images/v8/get_a_room.webp"
image helping_hand = "achievements/images/v8/helping_hand.webp"
image ip_man = "achievements/images/v8/ip_man.webp"
image lucky_7 = "achievements/images/v8/lucky_7.webp"
image text_with_an_s = "achievements/images/v8/text_with_an_s.webp"
image thick_and_thin = "achievements/images/v8/thick_and_thin.webp" # No corresponding achievement
image up_for_more = "achievements/images/v8/up_for_more.webp"

image relaxing_day = "achievements/images/v9/relaxing_day.webp"
image king_of_the_north = "achievements/images/v9/king_of_the_north.webp"
image back_down = "achievements/images/v9/back_down.webp"
image second_date = "achievements/images/v9/second_date.webp"
image the_wrong_time = "achievements/images/v9/the_wrong_time.webp"
image cheat_day = "achievements/images/v9/cheat_day.webp"

image fright_club = "achievements/images/v10/fright_club.webp"
image bros_before_blows = "achievements/images/v10/bros_before_blows.webp"
image rough_rider = "achievements/images/v10/rough_rider.webp"
image family_secrets = "achievements/images/v10/family_secrets.webp"
image golden_boy = "achievements/images/v10/golden_boy.webp"
image lights_out = "achievements/images/v10/lights_out.webp"
image getting_clean = "achievements/images/v10/getting_clean.webp"
image forbidden_romance = "achievements/images/v10/forbidden_romance.webp"
image hard_decisions = "achievements/images/v10/hard_decisions.webp"
image rawr_im_a_lion = "achievements/images/v10/rawr_im_a_lion.webp"
image on_the_court = "achievements/images/v10/onthecourt.webp"

image perry_mason = "achievements/images/v11/perry_mason.webp"
image candy_crusher = "achievements/images/v11/candy_crusher.webp"
image hold_your_horses = "achievements/images/v11/hold_your_horses.webp"
image off_your_high_horse = "achievements/images/v11/off_your_high_horse.webp"
image cross_your_heart = "achievements/images/v11/cross_your_heart.webp"
image on_target = "achievements/images/v11/on_target.webp"
image just_a_theory = "achievements/images/v11/just_a_theory.webp"
image fruity = "achievements/images/v11/fruity.webp"
image earn_your_owl = "achievements/images/v11/earn_your_owl.webp"
image political_strategist = "achievements/images/v11/political_strategist.webp"
image two_timer = "achievements/images/v11/two_timer.webp"
image dont_just_stand_there = "achievements/images/v11/dont_just_stand_there.webp"
image pretty_in_pink = "achievements/images/v11/pretty_in_pink.webp"
image good_vs_evil = "achievements/images/v12/good_vs_evil.webp"
image a_person_like_me = "achievements/images/v12/a_person_like_me.webp"
image zero_to_hero = "achievements/images/v12/zero_to_hero.webp"
image doctors_orders = "achievements/images/v12/doctors_orders.webp"
image mercy_killing = "achievements/images/v12/mercy_killing.webp"
image talk_murder_to_me = "achievements/images/v12/talk_murder_to_me.webp"
image best_for_last = "achievements/images/v12/best_for_last.webp"
image weapons_down = "achievements/images/v12/weapons_down.webp"
image killing_spree = "achievements/images/v12/killing_spree.webp"
image mass_casualties = "achievements/images/v12/mass_casualties.webp"
image thrown_to_the_lions = "achievements/images/v12/thrown_to_the_lions.webp"
image you_may_kiss_the_bride = "achievements/images/v12/you_may_kiss_the_bride.webp"
image a_bet_is_a_bet = "achievements/images/v12/a_bet_is_a_bet.webp"
image brotherhood_of_men = "achievements/images/v12/brotherhood_of_men.webp"
image best_frenemies = "achievements/images/v12/best_frenemies.webp"
image worth_the_wait = "achievements/images/v12/worth_the_wait.webp"
image inside_job = "achievements/images/v12/inside_job.webp"
image all_is_fair_in_love_and_war = "achievements/images/v12/all_is_fair_in_love_and_war.webp"
image city_of_love = "achievements/images/v12/city_of_love.webp"
image indecisive = "achievements/images/v13/indecisive.webp"
image funny_night = "achievements/images/v13/funny_night.webp"
image gentlemen_prefer_gingers = "achievements/images/v13/gentlemen_prefer_gingers.webp"
image flush_flush = "achievements/images/v13/flush_flush.webp"
image he_is_done = "achievements/images/v13/he_is_done.webp"
image urbanizer_womanizer = "achievements/images/v13/urbanizer_womanizer.webp"
image romantic_heart = "achievements/images/v13/romantic_heart.webp"
image bro_moment = "achievements/images/v13/bro_moment.webp"
image an_honest_liar = "achievements/images/v13/an_honest_liar.webp"
image we_like_them_wild = "achievements/images/v13/we_like_them_wild.webp"
image voyeur = "achievements/images/v13/voyeur.webp"
image dammit_emily = "achievements/images/v13/dammit_emily.webp"
image calm_down_big_fella = "achievements/images/v13/calm_down_big_fella.webp"

image ready_player_three = "achievements/images/v14/ready_player_three.webp"
image saving_ryans_privates = "achievements/images/v14/saving_ryans_privates.webp"
