screen patreon_credits(support_link):
    tag end_screen
    modal True
    style_prefix "patreon_credits"

    default image_path = "gui/end_screen/"

    add image_path + "patreon_credits_background.webp"

    viewport id "vp":
        mousewheel True
        draggable True
        ysize 700
        ypos 50

        vbox:
            xfill True

            text "KING" bold True

            null height 25

            text "Jordan Phillips"
            text "Daniel Xu"
            text "Kevin Montano"
            text "HaydenFromTarget"
            text "KelseyDrew"
            text "Aerodynamics"
            text "Thatazn"
            text "Jeremiah B"
            text "Dwayne Menefee"

            null height 50

            text "PRESIDENT" bold True

            null height 25

            text "TayZarGaming"
            text "biggy"
            text "Erik Quimby"
            text "pot101"
            text "Vengo"
            text "Chewy"
            text "Ali Bertan Erten"
            text "RyanMK666 "
            text "Victor Luu"
            text "WarDean"
            text "Matthias Bradshaw"
            text "Antjo"
            text "Matthew Wiersma"
            text "Nelson Chen"
            text "Michael Arias"
            text "DavidT"
            text "Code1558"
            text "BlodiMonki"
            text "Kevin Bender"
            text "Mitchell Jackstadt"
            text "0raXtEr"
            text "XO"
            text "Alejandro Perez"
            text "GullintheZungle"

            null height 50

            text "SENIOR" bold True

            null height 25

            text "Amani Mongane"
            text "Micah Edgar"
            text "棋 张"
            text "William Laux"
            text "Sleepless Xenon"
            text "Chef Fuger"
            text "Vencut Viewly"
            text "Paul House"
            text "Jo Le"
            text "Charles Santiago"
            text "Geir Morgen"
            text "AverageGOAT"
            text "Duncan Gerungan"
            text "Josh Buchholz"
            text "Adamites"
            text "BoostedScoobaru"
            text "hayden Garrard"
            text "Yehudah Davis"
            text "Dtownfan1 "
            text "Kevin Zhang"
            text "David Mather"
            text "Luis Juarez"
            text "Chris Rhyner"
            text "derphh"
            text "Yee Chou"
            text "Austin Larsen"
            text "Eunju "
            text "Knibble Chilling"
            text "Gleen"
            text "Iosefa Tausa"
            text "Alex"
            text "Ray Wilson"
            text "Hydra Fusions"
            text "StevePedroski "
            text "LOGODERKING"
            text "Emily Cline"
            text "maHAra87"
            text "Charles Tomozer"
            text "Brock "
            text "Its Poutine"
            text "Sudan Wallace Jr"
            text "Snozz"
            text "MAURICIO"
            text "Strykeout"
            text "Brett Crickman"
            text "Maxime Dissaux"
            text "DG"
            text "Jun Ulric"
            text "AllenGregg1996"
            text "Tim"
            text "Nate -Taylor"
            text "happydixiklo"
            text "Adrian Jones"
            text "tonymack21"
            text "QS_Hoot"
            text "Shakun164 "
            text "Matthew Ellerby"
            text "Jonas Pedersen"
            text "Kilro1"
            text "Instant Noodle"
            text "iceman_nrw"
            text "BankMan"
            text "Bumabär "
            text "Chase Hammer"
            text "Anthony Valencia"
            text "Chris noname"
            text "TheMilkman"
            text "remixax "
            text "Almsepp1"
            text "CW "
            text "Robert Grimes"
            text "Dan River"
            text "AggieSlimer"
            text "Kevin chamberlain"
            text "Cameron Leonard"
            text "Marzook"
            text "Hunter Yang"
            text "hopepeebrewin"
            text "Grinch"
            text "Angeal90"
            text "eric morentin"
            text "Jeremy Bolen"
            text "Jeff Torres"
            text "dr bryan"
            text "Ian Frank"
            text "Liam Nehiley"
            text "Costa Queixo"
            text "Life Quite Tough"
            text "Tacoboy"
            text "Tyler McCarty"
            text "Monodam"
            text "Rocker0224 "
            text "Samuel Madden"
            text "Joseph Miller"
            text "Ben Loftis"
            text "민석 채"
            text "Justin Recker"
            text "Léo Coiffard"
            text "Durze"
            text "Jimmy Gumz"
            text "RubberSoul"
            text "Joshua Pham"
            text "Chase Nelson"
            text "Toni Leino"
            text "James Grizzle "
            text "Malviris"
            text "Steven Carrasquel"
            text "Richard C"
            text "Lightthetorch97"
            text "Kevin A"
            text "idontknowmaybe"
            text "KcPiglet"
            text "Riah"
            text "B. Livingston"
            text "Casper Spandet"
            text "Josh"
            text "David Feldmeier"
            text "DrWoodJaBlowMe"
            text "ConstableBleep "
            text "healer56"
            text "B Walker"
            text "Noah Saylors"
            text "God"
            text "Jake Paas"
            text "Nastice"
            text "ethan hadler"
            text "Adam Thompson"
            text "Ace "
            text "Moises"
            text "Niels de Lange"
            text "marioanator"
            text "john daniel mccord"
            text "Aroyoxx1"
            text "Tad Stemen"
            text "Bob Sanders "
            text "ds"
            text "Spencer Barlow"
            text "Shaun Yazot"
            text "Liam Hunt"
            text "How do I Change this?"
            text "Robert Melton"
            text "Chase Thompson"
            text "erol"
            text "Agent 6279"
            text "Richard Hernandez"
            text "君彦 王"
            text "William de Rule"
            text "Adog060"
            text "Mccracken172"
            text "VinnyAhhh"
            text "JackyChan - Lauren"
            text "chanchunsang "
            text "Matthew Hwa"
            text "Joe "
            text "DaSnusMumrik"
            text "stef"
            text ""
            text "Jason Lackey"
            text "Flávio"
            text "bas vanwijken"
            text "Maxime Thibeault"
            text "Natyy"
            text "Zechicken119"
            text "Christian "
            text "seravee"
            text "Luke Grover"
            text "Daniel Brough"
            text "Matt Doe"
            text "Bruce"
            text "Andoraer Elantriss"
            text "KingHades1995"
            text "Spartan Clan"
            text "och0"
            text "Pat 5502"
            text "Luckey Beatz"
            text "Jim"
            text "Larsa Commons"
            text "Kalil Petties"
            text "Nathan Head"
            text "Dave Petit"
            text "Andrew Brick"
            text "Rodney H."
            text "skeiron911"
            text "Klaas Bosma"
            text "Ste"
            text "Arielle Thomas"
            text "Gryphon"
            text "liz"
            text "Ratchet Eshole"
            text "Christopher Gonzalez"
            text "Jedediah"
            text "Erlend "
            text "Aye3than"
            text "superbaat"
            text "Piet Müller"
            text "Riley Struck"
            text "james salcido"
            text "Mick Hout"
            text "jockelele"
            text "Samuel H"
            text "sickis121 "
            text "the_philosopher"
            text "Dovahbear "
            text "Muneeb Asad"
            text "Roman Solus"
            text "Zachary Livingston"
            text "Michael Bertini"
            text "Lennart"
            text "Steven "
            text "Muslim man"
            text "pete"
            text "David Garcia"
            text "BMF"
            text "leser"
            text "William "
            text "Oliver James"
            text "xOdin"
            text "c p"
            text "Taylor Hobbs"
            text "Leo"
            text "Marz "
            text "moutuxianyu "
            text "Rosco Todd"
            text "Quentin Chastain"
            text "Darren L"
            text "Charmy "
            text "James li"
            text "Valius86"
            text "Raja Chettiar "
            text "Itsgmg"
            text "Chadsgn"
            text "Colin Benson"
            text "Jacob Rumfield"
            text "Chance Porfily"
            text "Alexander garcia"
            text "Alexander Gonzalez"
            text "Beast Fam"
            text "Adrian Trussell"
            text "Christoph Schmidt"
            text "Trey"
            text "Tobias"
            text "Aaron Rogers"
            text "Payne309"
            text "AndrewHe "
            text "Amias Aurelia"
            text "Kevin Johnson"
            text "Wes Booth"
            text "Fazerogue2000 "
            text "Jason Ye"
            text "Sasa Markovic"
            text "Hddavidn"
            text "Yi Liu"
            text "Alpha Prime"
            text "Rodolfo Puig"
            text "Sasha"
            text "John Flynn"
            text "Tyler Cox"
            text "Sebastian Förster"
            text "MrUndeadNinja "
            text "Tom "
            text "Dario"
            text "Darnell "
            text "Mike Cotsalas"
            text "Cory R"
            text "Noah Meyeraan"
            text "Jordan Mitchell"
            text "Demetrius Blount"
            text "Erik fudge"
            text "Matt Cable"
            text "Pirorinnn"
            text "Floxyl"
            text "Mark Snyder"
            text "Chad White"
            text "Westy"
            text "Fume Knight Raime"
            text "Ken "
            text "Matthew Hull"
            text "Kis Zsolt"
            text "Tsukuru Tazaki"
            text "word001 "
            text "Daniel Huy Tran"
            text "Johnny"
            text "Ramiro Mendoza"
            text "Jeremy Armstrong"
            text "Guga"
            text "Madhatterdevoid "
            text "Bryan Lang"
            text "Owen"
            text "Blake55033"
            text "Mitchell Belcher"
            text "Florian Eckardt"
            text "IBkforever Gaming"
            text "Sj"
            text "Bob Eve"
            text "John"
            text "J"
            text "Tabris Sephir"
            text "kaiqi lu"
            text "Edward "
            text "Jacob B"
            text "George"
            text "Quanah"
            text "Sam"
            text "Logan"
            text "Jeria"
            text "Michael Heilig"
            text "Terry "
            text "Gilbert Mina"
            text "1337kaiz Buuuman"
            text "dominic gobeil"
            text "Demiurge "
            text "Brandon Bruseau"
            text "Sir Savynz"
            text "Rob Daystarr"
            text "Jason "
            text "minimat"
            text "Morten Kjeldsen"
            text "Tommy Gates"
            text "Breezy Trice"
            text "Xavier Williamson"
            text "Daniel Riley"
            text "shotz"
            text "Ryan Y"
            text "Thomas E Davis Jr"
            text "William Chandler"
            text "Dennis König"
            text "Kosu"
            text "Shane Mathis"
            text "Donald Kane"
            text "Thomas Trevino"
            text "Damien Norris"
            text "Asd"
            text "Jeremy Davis"
            text "Christian Halvorsen"
            text "Joshua Tam"
            text "lujinyi"
            text "Robin Borg"
            text "Jared"
            text "DragonSky "
            text "Chinh Lin"
            text "Greg Smith"
            text "General Fire"
            text "Space Cat"
            text "Pierre"
            text "Josh"
            text "Trent Brewer"
            text "Millie Guzman"
            text "Jasen "
            text "Alex Beamish"
            text "someguywhoplays"
            text "Tony Smith"
            text "Harrison Comish"
            text "Bernard How"
            text "Christoffer Jelsborg"
            text "RyanT9740"
            text "X Factr"
            text "lolisntaname "
            text "JohnPaul Summerall"
            text "Trent James Olslund"
            text "Erick Páez"
            text "nick magnum k"
            text "mjelo92"
            text "harrison thomasson"
            text "Josua Handoko"
            text "M.M."
            text "Shaun Cline"
            text "Kellarama"
            text "Daniel Folan"
            text "Hengst 2404"
            text "Andrew"
            text "Wladislaw Müller"
            text "Thomas G."
            text "Skatteverket"
            text "ammopackrat"
            text "Jeff Chase"
            text "Benjamin Lengauer"
            text "Qiuteng Ang"
            text "Joe "
            text "Bradley Lester"
            text "Sam "
            text "Logan Timmons"
            text "JamesIssacNeutron "
            text "Raumgar"
            text "Edward James"
            text "J79 "
            text "VladMyrrStudios"
            text "Lucylious"
            text "Charles"
            text "alex"
            text "Corey Gill"
            text "Philip"
            text "Tony Nguyen"
            text "freddie "
            text "DSS"
            text "W Barnes"
            text "Stefan Korisson"
            text "SeththeGOAT"
            text "SplashmanR6"
            text "Jonathan  Minjarez-Loera"
            text "Balls Of Iron"
            text "josh mcdaniel"
            text "Jake Rosen"
            text "LI YUXIN"
            text "J Lynch"
            text "Alexandre Rajotte"
            text "XR Capital"
            text "Rob Patchen"
            text "Yaxoba"
            text "Casey Lambert"
            text "SwankyOregano"
            text "gunner_ac "
            text "Richard Sehn"
            text "Sephix"
            text "Mokii"
            text "Yoken Worgen"
            text "Benjamin Corbett"
            text "Grant Killian"
            text "kirito232"
            text "Alex Handley"
            text "Sundae"
            text "reyesarsenal9"
            text "SS Patreon"
            text "Bo V."
            text "William C Smith"
            text "ShortBusBillsFan"
            text "Ozzy Biggin"
            text "Andrew Mendoza"
            text "moreorless"
            text "Alex "
            text "Muhammad Shoaib Memon"
            text "Evans Nguyen"
            text "Richie Tran"
            text "adam"
            text "Benoit Trottier"
            text "元 阮"
            text "Tyler Johnson"
            text "Harrison Quarls"
            text "Jake Hammer"
            text "Dylan"
            text "No Body"
            text "Erik Harvey"
            text "Kelvin Dartegnan"
            text "Matt Houck"
            text "cloudyHexs "
            text "Alex"
            text "Suki Saki"
            text "C "
            text "chris"
            text "FFavo"
            text "Shawn"
            text "Kjemm "
            text "Josh Dobson"
            text "ALEXSHKAD"
            text "Joseph Hrejsa Jr"
            text "Paul D Wood"
            text "Nick Simpson"
            text "Jamie Smith"
            text "Chris Schultz"
            text "Predatorx21"
            text "Roberto515"
            text "Erin"
            text "Ilan Sisouvanh"
            text "Arain"
            text "Billy Bob"
            text "Ballistic"
            text "David Menzies"
            text "nicholas Campbell"
            text "Nathjean"
            text "junior savior"
            text "Justin Nacionales"
            text "Brandon Moon"
            text "Snufti"
            text "michael"
            text "William Ou"
            text "Jeremy Brown"
            text "Sam"
            text "Cave Johnson"
            text "Soorya Bramhan"
            text "Kyle Kerrigan"
            text "Jonathan Hillard"
            text "GRRGomes "
            text "Dr.K"
            text "Matthew Journee"
            text "John MacLeod"
            text "Coffee Gang"
            text "Keith Mcchristy"
            text "R G"
            text "Erik Collazo"
            text "Jim Gannarelli"
            text "Taylor D"
            text "Federking "
            text "Iconas "
            text "Richard Martin"
            text "Matthew Wetton"
            text "The Tree"
            text "Wang Zhongchuan"
            text "Michaela Hill"
            text "Jimi Stephens"
            text "Ryan"
            text "fred "
            text "memo000"
            text "lt"
            text "Joshua Eldredge"
            text "Gravitysteal"
            text "Dakota Duerksen"
            text "Joshua Hughes"
            text "Ayaan Salman"
            text "Anthony Young"
            text "James keith"
            text "jiangming chen"
            text "bagel"
            text "Vin Liew"
            text "Brett Satterwhite"
            text "brthrbear "
            text "Nish Patel"
            text "Nik Ladner"
            text "Tom Weaver"
            text "Joopster"
            text "Goobie"
            text "Hunter Kratky"
            text "Evan Richman"
            text "Loui"
            text "thegamersigner"
            text "Andrew Basham"
            text "Pentaur"
            text "Patronus 123"
            text "Derrick Briand"
            text "Alexander Nicolet"
            text "Peeboboy"
            text "Fulcrum2187"
            text "Greg Cushman"
            text "Nikko"
            text "Liu Chengyu"
            text "Chris K"
            text "Camille"
            text "Nich Walker"
            text "Tyler Ressel"
            text "alex"
            text "theextrahammer"
            text "Gilthdorn "
            text "Jared Colalella"
            text "Nick Lehman"
            text "Matt"
            text "Corey jezek"
            text "joshuaapf"
            text "Elijah May"
            text "Henrik "
            text "Sam Doran"
            text "Jonathan Henry"
            text "drw"
            text "Faris "
            text "Yunxiang Zhang"
            text "Sebastian La Formica"
            text "Mike"
            text "13zedd"
            text "trong dan trinh"
            text "kevin"
            text "Surelysierra"
            text "Justin McCarthy"
            text "Bryton Kelley"
            text "David Egelund"
            text "Rand4here"
            text "Eric Jones"
            text "Jayton Essary"
            text "Chris Paul"
            text "Ren Pearson"
            text "Patrick Baird"
            text "Michael Armstrong"
            text "Ezio551199"
            text "DrSpideyRX"
            text "Smørblomst"
            text "MochaTeeni"
            text "IFL"
            text "matthew busby"
            text "Brian"
            text "Big jim"
            text "Eric Mendez"
            text "Hampus Kruska"
            text "Jacob Sytsma"
            text "jeremey "
            text "JC"
            text "Noah Michalski"
            text "MrTrashyKinz"
            text "Patrick Gregory"
            text "Aleksandar Jovanovic"
            text "John Karbowski"
            text "Nico Driller"
            text "Giorno Giovanna"
            text "Eagle2693"
            text "Iain McKenzie"
            text "James Prescott"
            text "Quanhao Yu"
            text "Chris Burrows"
            text "Tim"
            text "Esztergálos Péter"
            text "John Carlson"
            text "billabong"
            text "Coleman Johnson"
            text "Munkyi"
            text "Gitseht"
            text "Nate Wright"
            text "herbi"
            text "Markus Samida"
            text "Rcg01 "
            text "Zachary Tonkin"
            text "glossofblood"
            text "dakile98 "
            text "AntiChillTree"
            text "CCG Archmage"
            text "tony"
            text "Brandon Doyle"
            text "Michael Austin"
            text "Chad Grana"
            text "Bad Panda"
            text "Patrick Guerriero"
            text "Corey "
            text "Noel"
            text "Andre Pommer"
            text "Emanuel Muresan"
            text "Louis Kontakkis"
            text "Valdurial"
            text "trenton rogers"
            text "Zachary Ellis"
            text "Nate Sites"
            text "illeum"
            text "Warpigmain308"
            text "Shem "
            text "Ghost"
            text "Tyler s"
            text "Rathan01 "
            text "Ganderwiz"
            text "William Zaleppa"
            text "Scott"
            text "Blue"
            text "Beau Butler"
            text "Daniel Hernandez"
            text "Lou Gregoire"
            text "Gerrit nijenhuis"
            text "Steve B"
            text "Jesse Appleton"
            text "Cayce"
            text "Deadpool Lover"
            text "TheOtherGuy"
            text "Matt"
            text "Niles"
            text "David Huyler"
            text "June Lah"
            text "Wise"
            text "S7"
            text "Keegan Karr"
            text "logan dillie"
            text "WIlliam"
            text "Derick Garcia"
            text "Thedog"
            text "Nico Garcia"
            text "Kayla Danielle"
            text "Avery Orth"
            text "Stevev37"
            text "Morgan Hellström"
            text "Jesse Custer"
            text "jerome and Eli"
            text "Henceyyy"
            text "Steve H"
            text "Rory Storm Wahking"
            text "Eli Krell"
            text "Justin Wright"
            text "Friendlyfish"
            text "matg"
            text "Shane"
            text "Tom Michaels"
            text "Blake Mills"
            text "Katsu"
            text "mac bale"
            text "Jacques Heavy"
            text "A"
            text "Alex dempsey"
            text "ZacAttack"
            text "Lkiddoo"
            text "Kevin Marquez"
            text "Teddy Stimbach"
            text "Jacob Tompson-wright"
            text "robert mitchell"
            text "carlos"
            text "Erwin"
            text "Getoffmyname"
            text "Muhammad Furqan"
            text "Ma_Nans_NoseTrim"
            text "Strohmy86"
            text "Lauren's Boyfriend"
            text "Ace Seradilla"
            text "Haku"
            text "Nick Lenoy"
            text "Patrick "
            text "James Smithee"
            text "fivenights"
            text "Z "
            text "Connor Snitker"
            text "Avguste Antonov"
            text "GSM"
            text "Aizat Ahmad"
            text "Andreas H"
            text "Tyler Davis"
            text "SobrietyTest#6516"
            text "Inqxcel"
            text "Geoff Adams"
            text "Max"
            text "Logan Geisler"
            text "Wizard"
            text "craig Winstone"
            text "SEY"
            text "Rafael Batalla"
            text "n"
            text "HF110C "
            text "Majah Flavah"
            text "Abdul Qayyum"
            text "c cummins"
            text "Trent Seaward"
            text "A"
            text "George"
            text "Joseph Ricciardi"
            text "Sam"
            text "Levi Burns"
            text "Erik Heidemann-Staur"
            text "Luke Telford"
            text "Mark Jones"
            text "Whatever you want"
            text "Awkward Squad Productions"
            text "Stephan  Baker"
            text "Angel"
            text "Douglas Dreier"
            text "artie donovan"
            text "DeeCee Gaming"
            text "Monster114514 "
            text "Gerardo Contreras"
            text "Henrik Ophaug"
            text "Dave Davidson"
            text "CptSirBilLord"
            text "Andre Krieger"
            text "brandon matthews"
            text "LuckyU"
            text "Law"
            text "Dethwalker"
            text "Eugene Hudson"
            text "Ikta solork"
            text "Thomas Rebhandl"
            text "Idlerunner"
            text "Ali Izhar Ahmed"
            text "Derek Jones"
            text "Adam Sanno"
            text "Nick H"
            text "Shayne Meyer"
            text "RestfulLemur "
            text "Vlad Radu"
            text "Pionier 101"
            text "Andrew Stevens"
            text "Lumpacius"
            text "Chris"
            text "London Fazer Rider"
            text "Ali Jaafar"
            text "Hyndoue"
            text "alex holt"
            text "wilson cao"
            text "Martyn Kimber"
            text "Woodywood"
            text "Marcus Johnson"
            text "Ben Van Dyk"
            text "Ben Beatty"
            text "Sithriel Kobrock"
            text "Real612"
            text "Dave"
            text "Mark Hughes"
            text "정현"
            text "Hayden Troy"
            text "Brent "
            text "Michael Wang"
            text "foulesfall "
            text "Blackvein"
            text "Keep Paulo"
            text "Henrik Wallen"
            text "Tyson Dz"
            text "Nick Farley"
            text "Khan"
            text "Kyle McKinley"
            text "Noah Brand"
            text "Matt"
            text "James Giddens"
            text "Sean Marshall"
            text "Brody"
            text "David Allen Jr."
            text "BigDon"
            text "Sami Boukortt"
            text "BernieC"
            text "Noah Newmiller"
            text "Brocke Potts"
            text "Bryan Thurnau"
            text "Malthe Bentsen"
            text "Tyler Cipriani"
            text "Reta"
            text "Caleb Burch"
            text "Ceberskie"
            text "Zachary Trulson"
            text "Chase Schermerhorn"
            text "thelonelymountain"
            text "Alan Wong"
            text "Luke "
            text "ChopsthiCC"
            text "Nick Moonman"
            text "Philip Jones"
            text "Ryan Fleck"
            text "Carlos Palmer"
            text "Logan Sword"
            text "James Vavala"
            text "Shwavy"
            text "Michael Yearwood"
            text "Chris"
            text "Jake"
            text "Hey_Ty"
            text "smayotte1334"
            text "Nathan Liversedge"
            text "Robert Wolfe"
            text "Evan"
            text "Tanner Miller"
            text "asdf"
            text "Tom Gay"
            text "Dustin Polage"
            text "todash22"
            text "宇轩 夏"
            text "Weiss"
            text "XxSyreexX"
            text "Jeremiah Aldrin Evora"
            text "Dylan Chan"
            text "J "
            text "Devnerd"
            text "Josh"
            text "Steveyum "
            text "Patrick Wong"
            text "Scott Peart"
            text "Quinn Johnston"
            text "Antti Kananen"
            text "Gnosh "
            text "Joel Lim"
            text "ImToxic"
            text "Kyle Evans"
            text "shayne chevalier"
            text "Michael Urban"
            text "Kyle"
            text "Bastii"
            text "Bigfaze815"
            text "deathsnakeking"
            text "DriftDevil "
            text "Zed"
            text "EstuaryGuy "
            text "Miguel Emilio Basilio"
            text "lxtommy "
            text "Oscar Castillo"
            text "Lucas Desjardins"
            text "Andrew Derton"
            text "zxw"
            text "Brent Harris"
            text "Rab "
            text "Alex Chay"
            text "The Al_tissimo"
            text "Ben Smith"
            text "Eric Pettit"
            text "Mr Snowman"
            text "Nat"
            text "Natless"
            text "Pizza Delivery"
            text "mkn"
            text "Mike Jones"
            text "Amos Joe"
            text "Bob Smith"
            text "Justin meagher"
            text "Blake Harrison"
            text "Highender04"
            text "Ballistic Integrity"
            text "Chillhelm "
            text "Ethan S"
            text "Viktor Brunnström Rockborn"
            text "Ustierustie"
            text "Eugene Stadniciuc"
            text "Tytamice "
            text "Michael Oseguera"
            text "have2345"
            text "tbrown"
            text "Kira"
            text "Skraith"
            text "Dana Haywood"
            text "James Cross"
            text "Joshua"
            text "Darrell "
            text "Nolan Queen"
            text "Toby Schmidt"
            text "Palerider"
            text "WarzoneWally "
            text "Mitchell Trugoatsky"
            text "Pussy Destroyer"
            text "Steve Smart"
            text "Kane Croce"
            text "Michael Escobar"
            text "HurHallow"
            text "Thewatchstander"
            text "ty "
            text "Swen Engebretson"
            text "Peter Warming"
            text "Wan Cena"
            text "Romeo Salas"
            text "Stinkfinger877 "
            text "EntPlaysGames"
            text "Ben Price"
            text "Jason H"
            text "Ken Frischknecht"
            text "Christer Jonasson"
            text "Pacatl"
            text "Kyle9001"
            text "Kai Guy Incognito"
            text "Max Sleightholme"
            text "groove"
            text "Stormy Rain"
            text "Ethan Cornish"
            text "JAS647"
            text "Thomas Hotchkiss"
            text "Richard Gleizier"
            text "Brendan "
            text "Josh Foe"
            text "mtownsend18 ."
            text "Raymond Weijgertse"
            text "Blue"
            text "Chop Chop"
            text "Jon Johnson"
            text "ThreesDaily"
            text "Carl Marzo"
            text "John"
            text "Vivi"
            text "WaveU"
            text "용우 박"
            text "漢堡騎士"
            text "Soulyboy Hartley"
            text "Aaron"
            text "John David Keough"
            text "icam"
            text "Hampus Sahlsten"
            text "Kyal Cantwell"
            text "FrogHoppa "
            text "Joshua Conner"
            text "Nathan Rogers"
            text "Ørjan Rulnes Faane"
            text "Christian Jusino"
            text "Kyle Rogen"
            text "Pringles Riven"
            text "Zack "
            text "Jesus Flores"
            text "Lewis Miyawa"
            text "Meeks"
            text "Volves "
            text "Cole"
            text "Eren Poscez"
            text "Brian Vu"
            text "Andreas Hauge"
            text "Lhang Vang"
            text "Liam Bennett"
            text "NewInternSteve"
            text "Dom Romeo"
            text "McB"
            text "Jackson Michaelis"
            text "Allan Crocker"
            text "alex karolewski"
            text "Nicholas Loyd"
            text "Juan Lino"
            text "JD"
            text "Hav0c3 "
            text "Gary Clark "
            text "Rafael D. Coppola"
            text "Sam Turic"
            text "SsJooo"
            text "John Boyd"
            text "Marcelo Reyes"
            text "Noah Vandenbos"
            text "Bryan Chuen"
            text "DJ Dilleshaw"
            text "david gessey"
            text "Derek"
            text "Jordan P"
            text "Mystais "
            text "Simon08"
            text "Jack Brown"
            text "Noe Malagon"
            text "mark stevens"
            text "Travis "
            text "Leroy Lane"
            text "Wouter Goris"
            text "Steph Htr"
            text "JR "
            text "Markaus Berry"
            text "Shepley2183"
            text "Kuzco"
            text "Jason Hamersley"
            text "Goofy Gamer"
            text "BestNameEver "
            text "cges60508"
            text "Dale Jackson"
            text "Ed Wilder"
            text "Skyminions"
            text "Evan J. Williams"
            text "Kevin Doe"
            text "Chase Sparrow"
            text "Bootcolonel "
            text "Roldy Ebidag"
            text "Alien Hand"
            text "Jansoft"
            text "Deku"
            text "Louis"
            text "Faris Mufid"
            text "Shadi0"
            text "Connor Driscoll"
            text "Multibeast32"
            text "Christopher Ponce"
            text "Jacob Brown"
            text "JB93"
            text "Jose Hi"
            text "Elie"
            text "Charles Bohannan"
            text "TigerTheSaiyan "
            text "Dick "
            text "Benjamin Horne"
            text "Matt Stieve"
            text "Brett George"
            text "Silverwing "
            text "dawson poston"
            text "sa1001"
            text "tj boroff"
            text "Lillian Frost"
            text "Jonathan Hang"
            text "jordan strudwick"
            text "James Applegate"
            text "Jobin"
            text "Joseph M Smith"
            text "Mike"
            text "Squid Rockfish"
            text "BCM"
            text "Chien Kai Wang"
            text "Brian Maloney"
            text "Sewer Rat"
            text "James Ocaya"
            text "Tyler"
            text "Buh-Buh-Bacon "
            text "MegaManX"
            text "Rahul B S"
            text "Landon Patreon"
            text "Lithari"
            text "Joe"
            text "Myles Covert"
            text "John E Nebe"
            text "Yares Resya"
            text "Kieran Lay"
            text "Charles Hernandez"
            text "Matthias Kloeckner"
            text "Lochie Jamieson"
            text "Mr Blandin"
            text "Kevin Bernabe"
            text "Jay"
            text "Jay "
            text "Mjork"
            text "Josh"
            text "Bradley Bolt"
            text "Nick Benish"
            text "Winnehh Da Bambie"
            text "Mike B"
            text "Jordan Cassidy"
            text "冠希 陶"
            text "derek duchesneau"
            text "Alex Nowicki"
            text "Lucas"
            text "Nicholis Davis"
            text "Sawsbucky"
            text "Theodore Goodloe Richardson"
            text "JC"
            text "MaNiaK"
            text "Cameron Murray"
            text "SkyDriX .G"
            text "Connor"
            text "Jordan Walsh"
            text "Dillon Yeh"
            text "smokesgameplays "
            text "WarGodXimo "
            text "Jacob Nguyen"
            text "levy"
            text "Mcgalla"
            text "Alex Tallguy"
            text "Kevin Giuliano"
            text "Thiraphan Watcharotayan"
            text "david doyle"
            text "JJ Crowder"
            text "Tyler Montague"
            text "Luxuria Games"
            text "Ray"
            text "Cameron Pangborn"
            text "Robbie Fow"
            text "Voxals"
            text "Ostsalami"
            text "Smoke More"
            text "Panoramic Fx"
            text "Harry Smith"
            text "Nick Clarke"
            text "Nephilheim"
            text "SigvardsK"
            text "Son Goku"
            text "Tanner Gilbert"
            text "J Brennan"
            text "Fisken"
            text "Dowboi"
            text "Equinox"
            text "Kyle"
            text "Bombey's"
            text "Robert Ferrari"
            text "Adrian O'Leary"
            text "Jason Weiszhaar"
            text "H4LF-L3G1ON"
            text "Andre Olivier"
            text "Brandon Spears"
            text "Damien Jackson"
            text "Gerry Perez"
            text "Noel Gardner"
            text "TheMatze3112"
            text "Carlo Miguel Guevarra"
            text "Sleeplost"
            text "SilentHornet"
            text "Delos"
            text "Greg Safstrom"
            text "Richard W"
            text "Alexander "
            text "Adam Cossette"
            text "Matthew DiVincentiis"
            text "Thomas Summers"
            text "ryan gump"
            text "CallmeCap123 "
            text "Tha WhiteFang"
            text "Wayne Belliveau"
            text "Myron Nicolas"
            text "SHREDDER"
            text "esee1235"
            text "Dalton Ward"
            text "Eric Hugunin"
            text "gkek "
            text "Roberto Santillan "
            text "BO713"
            text "Anthony Roberts Jr"
            text "Swindlemark"
            text "Sam Smith"
            text "King Hugi"
            text "Doinitwrong "
            text "Alejandro Muniz"
            text "Matthew Iglehart"
            text "Steve Pizzaz"
            text "James chierchio"
            text "Mason Turner"
            text "Tony Lin"
            text "Edwin Park"
            text "Angelos Labrakis"
            text "J "
            text "Ledragon "
            text "K"
            text "Afiqfuddin Salleh"
            text "Nick"
            text "Ethan"
            text "Riley"
            text "David Stewart"
            text "Sam Meredith"
            text "Vernell Herbert"
            text "TRFCoast"
            text "Daniel Leathers"
            text "Peter Bauer"
            text "Troy Lensing"
            text "John Jimenez"
            text "JabbaTheBob"
            text "Isac Niklasson"
            text "Gustav Dahlberg"
            text "W1nz "
            text "Bush P Thach"
            text "Matthew Wrycza"
            text "Marco Delgado"
            text "Emil Johannsen"
            text "Lumbee_Bear"
            text "Johnathan Ortega"
            text "Ian "
            text "King"
            text "TortillaJackson"
            text "The Cheeky Dingo"
            text "imfromthe808 "
            text "Mathew "
            text "DDA80"
            text "Legends Of Flarrow"
            text "gazman"

    add "scene_gallery_bar_base" pos (1200, 50) xysize (27, 700)
    vbar:
        pos (1205, 55)
        xysize (17, 690)
        base_bar "#0000"
        thumb "gui/bar/bar_thumb.webp"
        value YScrollValue("vp")

    imagebutton:
        idle image_path + "support_development_idle.webp"
        hover image_path + "support_development_hover.webp"
        action OpenURL(support_link)
        xalign 0.5
        ypos 735

    hbox:
        align (0.5, 1.0)

        imagebutton:
            idle image_path + "main_menu_idle.webp"
            hover image_path + "main_menu_hover.webp"
            action MainMenu()
            yalign 0.5

        imagebutton:
            idle image_path + "team_idle.webp"
            hover image_path + "team_hover.webp"
            action Show("team_credits")
            yalign 0.5

    on "show" action [SetVariable("quick_menu", False), Play("music", "audio/music/common/vocal.mp3")]
    on "hide" action SetVariable("quick_menu", True)
    on "replace" action SetVariable("quick_menu", False)
    on "replaced" action SetVariable("quick_menu", True)


style patreon_credits_text is text:
    font "fonts/Montserrat-Regular.ttf"
    size 36
    xalign 0.5